-- Permissions seed SQL for hr-payroll
-- Generated from current PermissionSeeder permission groups

INSERT INTO `permissions` (`group_name`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES
('dashboard','View Dashboard','dashboard.view','View Dashboard',NOW(),NOW()),
('dashboard','Change Password Dashboard','dashboard.change-password','Change Password Dashboard',NOW(),NOW()),
('employee','View Employee','employee.view','View Employee',NOW(),NOW()),
('employee','Create Employee','employee.create','Create Employee',NOW(),NOW()),
('employee','Update Employee','employee.update','Update Employee',NOW(),NOW()),
('employee','Delete Employee','employee.delete','Delete Employee',NOW(),NOW()),
('employee','View Profile Employee','employee.view-profile','View Profile Employee',NOW(),NOW()),
('employee','View Hierarchy Employee','employee.view-hierarchy','View Hierarchy Employee',NOW(),NOW()),
('employee','Profile Update Request Submit Employee','employee.profile-update-request-submit','Profile Update Request Submit Employee',NOW(),NOW()),
('employee','Profile Update Request View Employee','employee.profile-update-request-view','Profile Update Request View Employee',NOW(),NOW()),
('employee','Profile Update Request Review Employee','employee.profile-update-request-review','Profile Update Request Review Employee',NOW(),NOW()),
('employee','Profile Update Request Approve Employee','employee.profile-update-request-approve','Profile Update Request Approve Employee',NOW(),NOW()),
('employee','Profile Update Request Reject Employee','employee.profile-update-request-reject','Profile Update Request Reject Employee',NOW(),NOW()),
('attendance','View Attendance','attendance.view','View Attendance',NOW(),NOW()),
('attendance','Clock Attendance','attendance.clock','Clock Attendance',NOW(),NOW()),
('attendance','Manage Attendance','attendance.manage','Manage Attendance',NOW(),NOW()),
('attendance','Approve Time Change Attendance','attendance.approve-time-change','Approve Time Change Attendance',NOW(),NOW()),
('attendance','Report Attendance','attendance.report','Report Attendance',NOW(),NOW()),
('attendance','Export Attendance','attendance.export','Export Attendance',NOW(),NOW()),
('attendance','Import Attendance','attendance.import','Import Attendance',NOW(),NOW()),
('attendance','Api Integration Attendance','attendance.api-integration','Api Integration Attendance',NOW(),NOW()),
('leave','View Leave','leave.view','View Leave',NOW(),NOW()),
('leave','Apply Leave','leave.apply','Apply Leave',NOW(),NOW()),
('leave','Approve Leave','leave.approve','Approve Leave',NOW(),NOW()),
('leave','Manage Categories Leave','leave.manage-categories','Manage Categories Leave',NOW(),NOW()),
('leave','Manage Quotas Leave','leave.manage-quotas','Manage Quotas Leave',NOW(),NOW()),
('leave','Manage Balances Leave','leave.manage-balances','Manage Balances Leave',NOW(),NOW()),
('leave','Report Leave','leave.report','Report Leave',NOW(),NOW()),
('payroll','View Payroll','payroll.view','View Payroll',NOW(),NOW()),
('payroll','Generate Payroll','payroll.generate','Generate Payroll',NOW(),NOW()),
('payroll','Manage Salary Templates Payroll','payroll.manage-salary-templates','Manage Salary Templates Payroll',NOW(),NOW()),
('payroll','Manage Bonus Payroll','payroll.manage-bonus','Manage Bonus Payroll',NOW(),NOW()),
('payroll','Manage Loan Payroll','payroll.manage-loan','Manage Loan Payroll',NOW(),NOW()),
('payroll','Manage Deduction Payroll','payroll.manage-deduction','Manage Deduction Payroll',NOW(),NOW()),
('payroll','Manage Pf Payroll','payroll.manage-pf','Manage Pf Payroll',NOW(),NOW()),
('payroll','Report Payroll','payroll.report','Report Payroll',NOW(),NOW()),
('bonus','View Bonus','bonus.view','View Bonus',NOW(),NOW()),
('bonus','Create Bonus','bonus.create','Create Bonus',NOW(),NOW()),
('bonus','Update Bonus','bonus.update','Update Bonus',NOW(),NOW()),
('bonus','Delete Bonus','bonus.delete','Delete Bonus',NOW(),NOW()),
('loan','View Loan','loan.view','View Loan',NOW(),NOW()),
('loan','Create Loan','loan.create','Create Loan',NOW(),NOW()),
('loan','Update Loan','loan.update','Update Loan',NOW(),NOW()),
('loan','Approve Loan','loan.approve','Approve Loan',NOW(),NOW()),
('loan','Delete Loan','loan.delete','Delete Loan',NOW(),NOW()),
('deduction','View Deduction','deduction.view','View Deduction',NOW(),NOW()),
('deduction','Create Deduction','deduction.create','Create Deduction',NOW(),NOW()),
('deduction','Update Deduction','deduction.update','Update Deduction',NOW(),NOW()),
('deduction','Approve Deduction','deduction.approve','Approve Deduction',NOW(),NOW()),
('deduction','Delete Deduction','deduction.delete','Delete Deduction',NOW(),NOW()),
('provident_fund','View Provident Fund','provident_fund.view','View Provident Fund',NOW(),NOW()),
('provident_fund','Post Transaction Provident Fund','provident_fund.post-transaction','Post Transaction Provident Fund',NOW(),NOW()),
('provident_fund','Adjust Provident Fund','provident_fund.adjust','Adjust Provident Fund',NOW(),NOW()),
('provident_fund','Report Provident Fund','provident_fund.report','Report Provident Fund',NOW(),NOW()),
('holiday','View Holiday','holiday.view','View Holiday',NOW(),NOW()),
('holiday','Create Holiday','holiday.create','Create Holiday',NOW(),NOW()),
('holiday','Update Holiday','holiday.update','Update Holiday',NOW(),NOW()),
('holiday','Delete Holiday','holiday.delete','Delete Holiday',NOW(),NOW()),
('department','View Department','department.view','View Department',NOW(),NOW()),
('department','Create Department','department.create','Create Department',NOW(),NOW()),
('department','Update Department','department.update','Update Department',NOW(),NOW()),
('department','Delete Department','department.delete','Delete Department',NOW(),NOW()),
('department','Assign Head Department','department.assign-head','Assign Head Department',NOW(),NOW()),
('designation','View Designation','designation.view','View Designation',NOW(),NOW()),
('designation','Create Designation','designation.create','Create Designation',NOW(),NOW()),
('designation','Update Designation','designation.update','Update Designation',NOW(),NOW()),
('designation','Delete Designation','designation.delete','Delete Designation',NOW(),NOW()),
('role','View Role','role.view','View Role',NOW(),NOW()),
('role','Create Role','role.create','Create Role',NOW(),NOW()),
('role','Update Role','role.update','Update Role',NOW(),NOW()),
('role','Delete Role','role.delete','Delete Role',NOW(),NOW()),
('role','Assign Role','role.assign','Assign Role',NOW(),NOW()),
('training','View Training','training.view','View Training',NOW(),NOW()),
('training','Create Training','training.create','Create Training',NOW(),NOW()),
('training','Update Training','training.update','Update Training',NOW(),NOW()),
('training','Delete Training','training.delete','Delete Training',NOW(),NOW()),
('award','View Award','award.view','View Award',NOW(),NOW()),
('award','Create Award','award.create','Create Award',NOW(),NOW()),
('award','Update Award','award.update','Update Award',NOW(),NOW()),
('award','Delete Award','award.delete','Delete Award',NOW(),NOW()),
('announcement','View Announcement','announcement.view','View Announcement',NOW(),NOW()),
('announcement','Create Announcement','announcement.create','Create Announcement',NOW(),NOW()),
('announcement','Publish Announcement','announcement.publish','Publish Announcement',NOW(),NOW()),
('announcement','Approve Announcement','announcement.approve','Approve Announcement',NOW(),NOW()),
('project','View Project','project.view','View Project',NOW(),NOW()),
('project','Create Project','project.create','Create Project',NOW(),NOW()),
('project','Update Project','project.update','Update Project',NOW(),NOW()),
('project','Delete Project','project.delete','Delete Project',NOW(),NOW()),
('project','Manage Members Project','project.manage-members','Manage Members Project',NOW(),NOW()),
('team','View Team','team.view','View Team',NOW(),NOW()),
('team','Create Team','team.create','Create Team',NOW(),NOW()),
('team','Update Team','team.update','Update Team',NOW(),NOW()),
('team','Delete Team','team.delete','Delete Team',NOW(),NOW()),
('team','Manage Members Team','team.manage-members','Manage Members Team',NOW(),NOW()),
('task','View Task','task.view','View Task',NOW(),NOW()),
('task','Create Task','task.create','Create Task',NOW(),NOW()),
('task','Update Task','task.update','Update Task',NOW(),NOW()),
('task','Delete Task','task.delete','Delete Task',NOW(),NOW()),
('task','Assign Task','task.assign','Assign Task',NOW(),NOW()),
('task','Comment Task','task.comment','Comment Task',NOW(),NOW()),
('note','View Private Note','note.view-private','View Private Note',NOW(),NOW()),
('note','Create Private Note','note.create-private','Create Private Note',NOW(),NOW()),
('note','Update Private Note','note.update-private','Update Private Note',NOW(),NOW()),
('note','Delete Private Note','note.delete-private','Delete Private Note',NOW(),NOW()),
('file','View File','file.view','View File',NOW(),NOW()),
('file','Upload File','file.upload','Upload File',NOW(),NOW()),
('file','Preview File','file.preview','Preview File',NOW(),NOW()),
('file','Comment File','file.comment','Comment File',NOW(),NOW()),
('file','Delete File','file.delete','Delete File',NOW(),NOW()),
('client','View Client','client.view','View Client',NOW(),NOW()),
('client','Create Client','client.create','Create Client',NOW(),NOW()),
('client','Update Client','client.update','Update Client',NOW(),NOW()),
('client','Delete Client','client.delete','Delete Client',NOW(),NOW()),
('estimate','View Estimate','estimate.view','View Estimate',NOW(),NOW()),
('estimate','Create Estimate','estimate.create','Create Estimate',NOW(),NOW()),
('estimate','Update Estimate','estimate.update','Update Estimate',NOW(),NOW()),
('estimate','Send Estimate','estimate.send','Send Estimate',NOW(),NOW()),
('estimate','Delete Estimate','estimate.delete','Delete Estimate',NOW(),NOW()),
('invoice','View Invoice','invoice.view','View Invoice',NOW(),NOW()),
('invoice','Create Invoice','invoice.create','Create Invoice',NOW(),NOW()),
('invoice','Update Invoice','invoice.update','Update Invoice',NOW(),NOW()),
('invoice','Send Invoice','invoice.send','Send Invoice',NOW(),NOW()),
('invoice','Record Payment Invoice','invoice.record-payment','Record Payment Invoice',NOW(),NOW()),
('invoice','Delete Invoice','invoice.delete','Delete Invoice',NOW(),NOW()),
('billing','View Billing','billing.view','View Billing',NOW(),NOW()),
('expense','View Expense','expense.view','View Expense',NOW(),NOW()),
('expense','Create Expense','expense.create','Create Expense',NOW(),NOW()),
('expense','Approve Expense','expense.approve','Approve Expense',NOW(),NOW()),
('expense','Pay Expense','expense.pay','Pay Expense',NOW(),NOW()),
('expense','Delete Expense','expense.delete','Delete Expense',NOW(),NOW()),
('expense','Report Expense','expense.report','Report Expense',NOW(),NOW()),
('report','View Report','report.view','View Report',NOW(),NOW()),
('report','Print Report','report.print','Print Report',NOW(),NOW()),
('report','Export Report','report.export','Export Report',NOW(),NOW()),
('notification','View Notification','notification.view','View Notification',NOW(),NOW()),
('notification','Send Notification','notification.send','Send Notification',NOW(),NOW()),
('audit','View Audit','audit.view','View Audit',NOW(),NOW()),
('settings','View Settings','settings.view','View Settings',NOW(),NOW()),
('settings','Update Settings','settings.update','Update Settings',NOW(),NOW())
ON DUPLICATE KEY UPDATE
`group_name` = VALUES(`group_name`),
`name` = VALUES(`name`),
`description` = VALUES(`description`),
`updated_at` = NOW();
